---
- name: deploy VM from template demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: VMVars.yaml
  tasks:
    - name: clone VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "MSwin - {{ item }}"
        folder: "{{ vcenter_destination_folder }}"
        template: "{{ vm_template }}"
        state: poweredoff
      loop: "{{ range(1, vm_count + 1, 1) | list }}"
